pull_request_rules:
  # - name: backport patches to cryostat-v2.3 branch
  #   conditions:
  #     - base=main
  #     - label=backport
  #   actions:
  #     backport:
  #       branches:
  #         - cryostat-v2.3
  #       assignees:
  #         - "{{ author }}"

  - name: request reviews from reviewers
    conditions:
      - label=ready-for-review
      - -changes-requested-reviews-by=maxcao13
    actions:
      request_reviews:
        users:
          - maxcao13
      comment: 
        message: This pull request is ready for review. @maxcao13

  - name: remove ready-for-review label
    conditions:
      - base=main
      - label=ready-for-review
      - changes-requested-reviews-by=maxcao13
    actions:
      label:
        remove:
          - ready-for-review

  - name: say hi to contributors if they are not part of the reviewers team
    conditions:
      - author!=maxcao13
    actions:
        comment:
          message: |
              Welcome to our great project!
              We're delighted to have you onboard 💘

  - name: auto label PRs from reviewers
    conditions:
      - author=maxcao13
    actions:
      label:
        add:
          - safe-to-test

  - name: dismiss stale reviews
    conditions:
      - base=main
    actions:
      dismiss_reviews:
        approved: from_requested_reviewers
        changes_requested: from_requested_reviewers
        message: |
          Pull request has been modified.
          Please apply the `ready-for-review` label again, or re-request reviews individually to notify us of your changes.

  - name: block pull requests that manually update web-client submodule
    conditions:
      - or:
        - files=path/to/web-client
        - files~=path/to/web-client/
    actions:
      review:
        type: REQUEST_CHANGES
        message: >-
            Pull Request blocked. `web-client` submodule updates are performed automatically by CI when that repository
            is updated. Please revert or drop all changes to the `web-client` submodule from this PR and perform any
            required frontend work by opening and merging a PR against
            [cryostat-web](https://github.com/cryostatio/cryostat-web).
      
  
